import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton } from "next/font/google";
import localFont from "next/font/local";
import AppWrapper from "@/components/globals/AppWrapper";
import { client } from "@/sanity/lib/client";
import { globalCTAQuery } from "@/sanity/lib/queries";
import "./globals.css";

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ppEditorialOld = localFont({
  variable: "--font-serif",
  src: [
    {
      path: "../public/fonts/PPEditorialOld-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/PPEditorialOld-Ultralight.woff2",
      weight: "200",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalCTA = await client.fetch(globalCTAQuery);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${ppEditorialOld.variable} antialiased bg-black`}
      >
        <AppWrapper globalCTA={globalCTA}>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
