/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type TwoColTextList = {
  _type: "twoColTextList";
  textCard?: TextCard;
  listItems?: Array<string>;
  alignTextVertically?: boolean;
  bgColor?: "none" | "black" | "white" | "lightGrey" | "darkGrey" | "offBlack";
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  headshot?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  content?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type AboutLandingPage = {
  _type: "aboutLandingPage";
  masthead?: {
    subheading?: string;
    heading?: string;
    description?: string;
    links?: LinksWrapper;
    leftTopImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
    leftBottomImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
    rightTopImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
    rightBottomImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
  };
  ourMission?: {
    subheading?: string;
    heading?: string;
    images?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
      _key: string;
    }>;
  };
  whyWeExist?: {
    heading?: string;
    content?: BlockContent;
  };
  ourJourney?: {
    heading?: string;
    content?: BlockContent;
    links?: LinksWrapper;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
  };
  ourValues?: {
    heading?: string;
    values?: Array<{
      icon?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        altText?: string;
        _type: "image";
      };
      heading?: string;
      description?: string;
      _type: "value";
      _key: string;
    }>;
  };
  meetTheTeam?: {
    heading?: string;
    teamMembers?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "teamMember";
    }>;
  };
};

export type GlobalOptions = {
  _id: string;
  _type: "globalOptions";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  contactEmail?: string;
  contactMobile?: string;
  companyAddress?: BlockContent;
  instagramUrl?: string;
  linkedinUrl?: string;
};

export type ImageGrid = {
  _type: "imageGrid";
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
    _key: string;
  }>;
};

export type TimedAccordionSlider = {
  _type: "timedAccordionSlider";
  items?: Array<{
    heading?: string;
    content?: BlockContent;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
    _key: string;
  }>;
};

export type ContactLandingPage = {
  _type: "contactLandingPage";
  heading?: string;
  description?: string;
  whyUs?: BlockContent;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  logoMarqueeBlock?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "reusableBlock";
  };
};

export type LandingPage = {
  _id: string;
  _type: "landingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  template?: "contact" | "about";
  contactLandingPage?: ContactLandingPage;
  aboutLandingPage?: AboutLandingPage;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type LinksWrapper = Array<{
  _key: string;
} & Link>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type GlobalCTA = {
  _type: "globalCTA";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
  heading?: string;
  description?: string;
  link?: {
    url?: string;
    title?: string;
  };
};

export type CaseStudyImage = {
  _type: "caseStudyImage";
  type?: "image" | "video";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  video?: string;
  videoPoster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  videoOptions?: {
    title?: string;
  };
};

export type CaseStudyRichText = {
  _type: "caseStudyRichText";
  content?: BlockContent;
};

export type CaseStudyBuilder = {
  _type: "caseStudyBuilder";
  title?: string;
  components?: Array<{
    _key: string;
  } & CaseStudyRichText | {
    _key: string;
  } & CaseStudyImage>;
};

export type StudioCarousel = {
  _type: "studioCarousel";
  studios?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "studio";
  }>;
};

export type Studio = {
  _id: string;
  _type: "studio";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  features?: Array<string>;
};

export type FeatureCards = {
  _type: "featureCards";
  layout?: "twoCols" | "threeCols" | "fourCols";
  type?: "numbered";
  features?: Array<{
    icon?: "none";
    title?: string;
    description?: string;
    _type: "feature";
    _key: string;
  }>;
};

export type SelectedWorks = {
  _type: "selectedWorks";
  caseStudies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
};

export type HeaderMarquee = {
  _type: "headerMarquee";
  items?: Array<string>;
};

export type LinkCards = {
  _type: "linkCards";
  layout?: "twoCols" | "threeCols" | "fourCols";
  links?: Array<{
    title?: string;
    url?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
    };
    _type: "link";
    _key: string;
  }>;
};

export type Logos = {
  _type: "logos";
  type?: "marquee" | "grid";
  label?: string;
  labelPlacement?: "stacked" | "side";
  logoMarqueeBlock?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "reusableBlock";
  };
  invertLogos?: boolean;
};

export type TwoColTextAsset = {
  _type: "twoColTextAsset";
  textCard?: TextCard;
  asset?: Asset;
  alignTextVertically?: boolean;
  reverseDirection?: boolean;
};

export type Asset = {
  _type: "asset";
  id?: string;
  type?: "image" | "video";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
  video?: string;
  videoPoster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
  videoOptions?: {
    title?: string;
    showTitleOnPoster?: boolean;
  };
};

export type LogoMarquee = {
  _type: "logoMarquee";
  title?: string;
  logos?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    link?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Link = {
  _type: "link";
  type?: "button" | "textLink";
  buttonSize?: "default" | "sm" | "lg";
  buttonStyle?: "primary" | "outline" | "accent";
  url?: string;
  label?: string;
};

export type TextCardOptions = {
  _type: "textCardOptions";
  centerAlign?: boolean;
  centerAlignOnMobile?: boolean;
  subheadingTag?: "h1" | "h2" | "h3" | "h4" | "h5";
  headingTag?: "h1" | "h2" | "h3" | "h4" | "h5";
  headingFontSize?: "24px" | "40px" | "80px" | "100px" | "120px";
  headingMaxWidth?: number;
  contentFontSize?: "default" | "md" | "lg";
  contentMaxWidth?: number;
  listType?: "bullet" | "tick";
};

export type TextCard = {
  _type: "textCard";
  subheading?: string;
  heading?: string;
  content?: BlockContent;
  links?: LinksWrapper;
  textCardOptions?: TextCardOptions;
};

export type TwoColMasthead = {
  _type: "twoColMasthead";
  subheading?: string;
  heading?: string;
  content?: string;
  links?: LinksWrapper;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
};

export type HomeMasthead = {
  _type: "homeMasthead";
  heading?: string;
  content?: string;
  links?: LinksWrapper;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
  addLogoMarquee?: boolean;
  logoMarquee?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "reusableBlock";
  };
};

export type ReusableBlock = {
  _id: string;
  _type: "reusableBlock";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  type?: "logoMarquee" | "globalCTA";
  logoMarquee?: LogoMarquee;
  globalCTA?: GlobalCTA;
};

export type Masthead = {
  _type: "masthead";
  type?: "home" | "services" | "about";
  heading?: string;
  content?: string;
  links?: LinksWrapper;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  excerpt?: string;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  date?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  video?: string;
  videoType?: "normal" | "short";
  content?: Array<{
    _key: string;
  } & CaseStudyBuilder>;
};

export type SectionOptions = {
  _type: "sectionOptions";
  id?: string;
  bgColor?: "none" | "black" | "white" | "lightGrey" | "darkGrey" | "offBlack";
  removeContainer?: boolean;
  isContainedSection?: boolean;
  containedBgColor?: "none" | "black" | "white" | "lightGrey" | "darkGrey" | "offBlack";
  paddingTop?: "none" | "xs" | "sm" | "md" | "lg";
  paddingBottom?: "none" | "xs" | "sm" | "md" | "lg";
  marginTop?: "none" | "xs" | "sm" | "md" | "lg";
  marginBottom?: "none" | "xs" | "sm" | "md" | "lg";
  componentSpacing?: "default" | "sm" | "md" | "lg";
  overflow?: "hidden" | "visible";
  addBottomDivider?: boolean;
};

export type Section = {
  _type: "section";
  title?: string;
  components?: Array<{
    _key: string;
  } & Masthead | {
    _key: string;
  } & HomeMasthead | {
    _key: string;
  } & TwoColMasthead | {
    _key: string;
  } & TextCard | {
    _key: string;
  } & Asset | {
    _key: string;
  } & TwoColTextAsset | {
    _key: string;
  } & Logos | {
    _key: string;
  } & LinkCards | {
    _key: string;
  } & HeaderMarquee | {
    _key: string;
  } & SelectedWorks | {
    _key: string;
  } & FeatureCards | {
    _key: string;
  } & StudioCarousel | {
    _key: string;
  } & TimedAccordionSlider | {
    _key: string;
  } & ImageGrid | {
    _key: string;
  } & TwoColTextList>;
  sectionOptions?: SectionOptions;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: Array<{
    _key: string;
  } & Section>;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = TwoColTextList | TeamMember | BlockContent | SanityImageCrop | SanityImageHotspot | AboutLandingPage | GlobalOptions | ImageGrid | TimedAccordionSlider | ContactLandingPage | LandingPage | Seo | LinksWrapper | Slug | GlobalCTA | CaseStudyImage | CaseStudyRichText | CaseStudyBuilder | StudioCarousel | Studio | FeatureCards | SelectedWorks | HeaderMarquee | LinkCards | Logos | TwoColTextAsset | Asset | LogoMarquee | Link | TextCardOptions | TextCard | TwoColMasthead | HomeMasthead | ReusableBlock | Masthead | Category | Project | SectionOptions | Section | Page | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
